export enum WEIGHT_STATION {
  SCALE_1_CB_1 = 'SCALE-1-CB-1',
  SCALE_1_CB_2 = 'SCALE-1-CB-2',
  SCALE_1_CB_3 = 'SCALE-1-CB-3',
  SCALE_1_CB_4 = 'SCALE-1-CB-4',

  SCALE_1_STATUS = 'SCALE_1_STATUS',
  SCALE_1_BALANCE = 'SCALE_1_BALANCE',
  VEHICLE_1_STATUS = 'VEHICLE_1_STATUS',
  Notification = 'Notification',
  ENABLED_RFID_1_STATUS = 'ENABLED_RFID_1_STATUS',
  ENABLED_RFID_1_TIME = 'ENABLED_RFID_1_TIME',
  LOCKING_RFID_1_STATUS = 'LOCKING_RFID_1_STATUS',
  SCALE_1_IS_LOCKING_RFID = 'SCALE_1_IS_LOCKING_RFID',
  SCALE_1_CURRENT_RFID = 'SCALE_1_CURRENT_RFID',
}

export enum WEIGHT_STATION_2 {
  SCALE_2_CB_1 = 'SCALE-2-CB-1',
  SCALE_2_CB_2 = 'SCALE-2-CB-2',
  SCALE_2_CB_3 = 'SCALE-2-CB-3',
  SCALE_2_CB_4 = 'SCALE-2-CB-4',

  SCALE_2_STATUS = 'SCALE_2_STATUS',
  SCALE_2_BALANCE = 'SCALE_2_BALANCE',
  VEHICLE_2_STATUS = 'VEHICLE_2_STATUS',
  Notification = 'Notification',
  ENABLED_RFID_2_STATUS = 'ENABLED_RFID_2_STATUS',
  ENABLED_RFID_2_TIME = 'ENABLED_RFID_2_TIME',
  LOCKING_RFID_2_STATUS = 'LOCKING_RFID_2_STATUS',
  SCALE_2_IS_LOCKING_RFID = 'SCALE_2_IS_LOCKING_RFID',
  SCALE_2_CURRENT_RFID = 'SCALE_2_CURRENT_RFID',
}
